# Generated by Django 5.2.15 on 2026-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_document_file_alter_document_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
